call_parentheses = "Always"
collapse_simple_statement = "Never"
column_width = 120
indent_type = "Spaces"
indent_width = 2
line_endings = "Unix"
no_call_parentheses = false
quote_style = "AutoPreferSingle"
space_after_function_names = "Never"
syntax = "All"

[sort_requires]
enabled = false
