[[mgr.prepend_keymap]]
on = "l"
run = "plugin smart-enter"
desc = "Enter directory or open file"

[[mgr.prepend_keymap]]
on = "<Enter>"
run = "plugin smart-enter"
desc = "Enter directory or open file"

[[mgr.prepend_keymap]]
on = "f"
run = "plugin smart-filter"
desc = "Smart filter"

[[mgr.prepend_keymap]]
on = "<C-h>"
run = "hidden toggle"
desc = "Toggle hidden files"

[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"

[[mgr.prepend_keymap]]
on = "Y"
run = '''shell 'for path in "$@"; do echo -n "$path"; done | pbcopy' --confirm'''
desc = "Yank full path"

[[mgr.prepend_keymap]]
on = "S"
run = "shell '$SHELL' --block --confirm"
desc = "Open shell here"

[[mgr.prepend_keymap]]
on = "e"
run = "shell '$EDITOR \"$@\"' --block --confirm"
desc = "Edit with $EDITOR"

[[mgr.prepend_keymap]]
on = "+"
run = "plugin zoom 1"
desc = "Zoom in hovered file"

[[mgr.prepend_keymap]]
on = "-"
run = "plugin zoom -1"
desc = "Zoom out hovered file"
