[mgr]
linemode = "size"
ratio = [1, 3, 4]
show_hidden = true
sort_by = "natural"
sort_dir_first = true

[opener]
edit = [
  { run = 'nvim "$@"', block = true, for = "unix" },
]

[[plugin.prepend_previewers]]
url = "*.ans"
run = "ansi-preview"

[[plugin.prepend_previewers]]
url = "*.ansi"
run = "ansi-preview"

[[plugin.prepend_fetchers]]
id  = "git"
url = "*"
run = "git"

[[plugin.prepend_fetchers]]
id  = "git"
url = "*/"
run = "git"
