[theme]
dark = "catppuccin_mocha_transparent"
light = "catppuccin_latte"
fallback = "catppuccin_mocha_transparent"

[editor]
mouse = true
line-number = "relative"
cursorline = true
bufferline = "always"
rulers = [80, 100, 120]
color-modes = true
trim-final-newlines = true
trim-trailing-whitespace = true
rainbow-brackets = true

[editor.lsp]
display-progress-messages = true
display-inlay-hints = true
display-color-swatches = true
inlay-hints-length-limit = 40

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.auto-save]
focus-lost = true

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "hint"

[editor.word-completion]
enable = true
trigger-length = 5

[editor.file-explorer]
hidden = false
git-ignore = true
flatten-dirs = true

[editor.buffer-picker]
start-position = "previous"

[editor.statusline]
diagnostics = ["error", "warning", "info", "hint"]
workspace-diagnostics = ["error", "warning"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
#  https://github.com/helix-editor/helix/discussions/5764#discussioncomment-12968177
"A-j" = [
  "extend_to_line_bounds",
  "delete_selection",
  "paste_after",
  "select_mode",
  "goto_line_start",
  "normal_mode",
] # Move line(s) down
"A-k" = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
  "flip_selections",
] # Move line(s) up
"C-k" = [
  ":insert-output sh -c \"echo -n $(date +'%%Y-%%m-%%d %%H:%%M:%%S')\"",
  "collapse_selection",
  "move_char_right",
]
"C-g" = [
  ":new",
  ":insert-output lazygit",
  ":buffer-close!",
  ":redraw",
]
"C-r" = [":reload-all"]

[keys.normal."space"]
"e" = "file_explorer_in_current_buffer_directory"
"S-e" = "file_explorer_in_current_directory"
"f" = "file_picker"
"S-f" = "file_picker_in_current_directory"

[keys.insert]
"esc" = [":write", "normal_mode"]
"C-k" = [
  ":insert-output sh -c \"echo -n $(date +'%%Y-%%m-%%d %%H:%%M:%%S')\"",
  "collapse_selection",
  "move_char_right",
]
